//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalmarBSK.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingParticipant
    {
        public int Id { get; set; }
        public int GameLocationId { get; set; }
        public int PersonId { get; set; }
    
        public virtual GameLocation GameLocation { get; set; }
        public virtual Personer Personer { get; set; }
    }
}
